### ISSUE TITLE
Inset Inline Properties not being applied

### ISSUE THREAD

**Issue by K3TH3R** [stevecochrane/tailwindcss-logical#31]
I'm in the process of migrating a small app build over to logical properties. Everything has largely gone smoothly, but I've run into one issue with the inset inline properties. I am seeing the actual class in my VSCode Intellisense:

![Screen Shot 2022-03-01 at 10 43 07 am](https://user-images.githubusercontent.com/11901111/156077926-47231bc1-ed49-4289-8511-15e61da157a4.png)

![Screen Shot 2022-03-01 at 11 19 17 am](https://user-images.githubusercontent.com/11901111/156080856-54adb032-23bb-412a-bbf0-cf7df3f60133.png)

I thought it might be something with JIT/purgeCSS, but I'm not running into any issues with any other of the `tailwindcss-logical` classes so far. Everything else, including the `inset-inline-` classes are working and being applied in the HTML, but I can't get the `inline-start-` and `inline-end-` classes to be applied.

[Edit]
Also seeing this on:
- `border-ie-*` classes

**Comment by K3TH3R** [comment]
@stevecochrane Thanks. I've tried recreating a minimal example repo for you and I can't seem to replicate it, so it must be some weirdness in my main project.

**Comment by K3TH3R** [comment]
I'm going to add this in here as documentation for anyone else that might run into this in the future. The problem appears to lie not with `tailwindcss-logical`, so much as it does with `postcss-preset-env`. I was seeing unnecessary color overrides on my inline border classes which were wiping out my CSS custom property values:
![Screen Shot 2022-03-17 at 9 49 13 am](https://user-images.githubusercontent.com/11901111/158707344-d6e0a2e2-8046-487a-b70b-4ffe13b759b9.png)

Simply commenting out `postcss-preset-env` from my `postcss.config.js` file fixed the problem. I'm still working on narrowing down how/why this is happening within `preset-env` and plan to open a ticket over there once I have it figured out, but wanted to add this for now in case anyone else bumps into this problem.

**Comment by stevecochrane** [comment]
Interesting, and this is good to know about since `postcss-preset-env` is very commonly used. Thank you for sharing this!
