### ISSUE TITLE
Tailwind 3.3 logical release

### ISSUE THREAD

**Issue by vltansky** [stevecochrane/tailwindcss-logical#38]
https://tailwindcss.com/blog/tailwindcss-v3-3#simplified-rtl-support-with-logical-properties

as tailwind released logical properties. I think this package readme should recommend using the out of the box support.

**Comment by stevecochrane** [comment]
Hi @vltansky, I just saw the announcement too, thanks for letting me know. I agree that it's best to recommend the native support options now, so I've just added a note near the top of the README. Does that look good? Let me know if there's anything else you have in mind.

As for what happens next, I'm going to compare the native support with this plugin and see what the differences are like. It might make sense to continue supporting this plugin with a new major version where the overlapping parts are removed, in case people still need the properties and values that don't yet have official support. I still have some things to think about, but I'm open to suggestions here too.
