### ISSUE TITLE
There's no support to responsive utilities

### ISSUE THREAD

**Issue by Ayman97** [stevecochrane/tailwindcss-logical#9]
Hey
Can you please add support to responsive utilities like space / margin and padding?

**Comment by Ayman97** [comment]
Turns out i can make add responsive variants in tailwind.config.js file 😅

**Comment by stevecochrane** [comment]
Hi @Ayman97,

Yep, you've got it! :) It's pretty buried in the README at the moment and I might want to move this information up, but adding the responsive variants to tailwind.config.js should work like this:

```
// tailwind.config.js
module.exports = {
  variants: {
    logical: ['responsive', 'hover']
  }
}
```

That said, if you do encounter any issues when adding responsive variants like this, just let me know and I'll take a look.

**Comment by abublihi** [comment]
Thank you for the awesome repo,

but the docs did not clear what variants are available, for example if i add the  next lines to the tailwind config file
```
// tailwind.config.js
module.exports = {
  variants: {
    logical: ['responsive', 'hover']
  }
}
```

then things like `inline-end-0` won't work.
